#!/bin/bash
#
# Malloc Detective: Main
#
# Usage
#   ./malloc_detective [-f] [-o output file] prog [arg..]
#   -f : Trace child process.
#   -F : Output free()'s backtrace. (default: off)
#   -o <output file> : Switch output stream if set this options.
#                      (default: STDERR)
#
# Output format:
#   [timestamp] [PID] [kind] [address] [size] [backtrace ..]
#   (separator is TAB)
#
# ---------------------------------------------------------------------------
# Copyright (c) 2015 Ayumu Koujiya
#
# Permission is hereby granted, free of charge, to any person obtaining a copy 
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the 
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

usage_exit() {
    echo "Usage: $0 [-f] [-o output file] prog [arg..]" 1>&2
    exit 1
}

while getopts fFo:h OPT; do
    case $OPT in
    f)  export MALLOC_DETECTIVE_CHILD=1
        ;;
    F)  export MALLOC_DETECTIVE_FREE=1
        ;;
    o)  export OUTPUT_FILE=$OPTARG
        ;;
    h)  usage_exit
        ;;
    esac
done
shift $(($OPTIND - 1))
[ $# -le 0 ] && usage_exit

WRAPPER_SO="$(dirname $0)/malloc_detective.so"

if [ "_$OUTPUT_FILE" = "_" ]; then
    LD_PRELOAD="$WRAPPER_SO" "$@"
else
    export MALLOC_DETECTIVE_OUTPUT=pipe.malloc_wrapper_pipe.$$
    trap "/bin/rm $MALLOC_DETECTIVE_OUTPUT" EXIT
    mkfifo $MALLOC_DETECTIVE_OUTPUT
    cat $MALLOC_DETECTIVE_OUTPUT > $OUTPUT_FILE &
    LD_PRELOAD="$WRAPPER_SO" "$@"
fi

# vim: ts=4 sts=4 sw=4 expandtab

